// UI strings. English is the default; Brazilian Portuguese and German are selectable in the settings.
// Strings.t(key) is resolved by the Strings singleton in QML; here are the tables only.
.pragma library

var languages = ["en", "pt_BR", "de"]

var table = {
    pt_BR: {
        title: "Operação TI", subtitle: "Defenda o Datacenter",
        play: "Jogar", howto: "Como jogar", settings: "Ajustes", back: "Voltar", resume: "Continuar", restart: "Reiniciar",
        quit: "Sair", ok: "Entendi", close: "Fechar",
        premise: "Sexta-feira, 17h. A equipe de TI já ia embora quando o painel de monitoramento acendeu.\nMantenha o datacenter online até o incidente ser resolvido!",
        credits: "Créditos", health: "Saúde do Serviço", wave: "Onda", enemies: "Ameaças", remaining: "restantes",
        startWave: "Iniciar onda", nextWave: "Próxima onda", speedNormal: "1x", speedFast: "2x", pause: "Pausa", paused: "Jogo pausado",
        build: "Construir", upgrade: "Melhorar", sell: "Vender", cancel: "Cancelar", level: "Nível", max: "Máx.",
        range: "Alcance", damage: "Dano", rate: "Disparos/s", slow: "Lentidão", splash: "Área", boost: "Turbo", period: "A cada",
        reboot: "Reboot de Emergência", rebootHint: "Toque no mapa: as torres na área reiniciam (3 s offline) e voltam limpas e mais rápidas.",
        rebootReady: "Pronto", rebootCooldown: "Recarregando", rebootEmpty: "Nenhuma torre nessa área.",
        noCredits: "Créditos insuficientes.", occupied: "Este ponto já tem uma torre.", placeHere: "Toque em um ponto azul para construir.",
        victory: "Incidente resolvido!", victoryText: "O datacenter continuou online. Bom fim de semana, equipe!",
        defeat: "O serviço caiu…", defeatText: "Acontece com todo mundo. Reinicie e tente uma combinação diferente de torres.",
        best: "Melhores resultados", bestWave: "Melhor onda", wins: "Vitórias", fastest: "Vitória mais rápida", none: "—",
        language: "Idioma", volume: "Volume", mute: "Mudo", reducedFx: "Menos efeitos", on: "Ligado", off: "Desligado",
        socket: "Ponto de instalação", socketHint: "Escolha uma torre abaixo. O círculo mostra o alcance antes de comprar.",
        hint_corners: "Cobre duas passagens da rota.", hint_splash: "Ótimo para dano em área.", hint_support: "Perto de outras torres: bom para suporte.",
        hint_range: "Longe da rota: prefira alcance grande.", hint_entrance: "Perto da entrada: as ameaças ainda estão juntas.",
        disabled: "Bloqueada", offline: "Reiniciando", incoming: "A caminho", ready: "Pronto?",
        tower_patch: "Estação de Patch", tower_patch_desc: "Um notebook de técnico. Dispara pulsos de dados em uma ameaça por vez. Barata e confiável.",
        tower_firewall: "Firewall", tower_firewall_desc: "Um equipamento robusto com painel de escudo. Rajadas curtas que atingem grupos.",
        tower_traffic: "Controlador de Tráfego", tower_traffic_desc: "Um switch de rede. Deixa as ameaças próximas mais lentas por alguns segundos (no máximo 50%).",
        tower_scanner: "Scanner de Segurança", tower_scanner_desc: "Um monitor de varredura. Revela ameaças ocultas no alcance e causa dano moderado.",
        tower_backup: "Estação de Backup", tower_backup_desc: "Um nobreak. Não ataca: de tempos em tempos dá turbo de velocidade a uma torre vizinha.",
        enemy_bug: "Bug", enemy_bug_desc: "Um bloquinho laranja travesso. Comum, velocidade e vida médias.",
        enemy_spam: "Pacote de Spam", enemy_spam_desc: "Um envelope amarelo apressado. Rápido e frágil, vem em bandos.",
        enemy_trojan: "Pacote Trojan", enemy_trojan_desc: "Uma caixa roxa com costura suspeita. Ao ser derrotada solta 3 Bugs!",
        enemy_stealth: "Pacote Oculto", enemy_stealth_desc: "Um losango ciano quase invisível. Só pode ser atingido enquanto um Scanner o revela.",
        enemy_lock: "Ransomware", enemy_lock_desc: "Um cadeado vermelho pesado. Lento, resistente e bloqueia uma torre próxima por alguns segundos.",
        enemy_boss: "Deploy de Sexta", enemy_boss_desc: "Um pacote de software instável e gigante. Lento, e solta bandos de Spam ao perder vida.",
        w1: "Alguém clicou no anexo.", w2: "Funcionava em homologação.", w3: "O estagiário rodou o script em produção.", w4: "Caixa de entrada: 9.999 novas mensagens.",
        w5: "“É só um pacotinho, confia.”", w6: "Manutenção de emergência!", w7: "Presente de grego.", w8: "O fornecedor jura que é seguro.",
        w9: "Tráfego suspeito no switch 3.", w10: "Tem algo se escondendo nos logs…", w11: "O antivírus está “atualizando”.", w12: "Ninguém lê o changelog.",
        w13: "Seus arquivos foram… espera, não!", w14: "Backup? Que backup?", w15: "Deploy de sexta-feira.",
        teach_place: "Toque em um ponto azul ao lado da rota e escolha uma torre. O círculo mostra o alcance antes de gastar.",
        teach_patch: "Comece com a Estação de Patch: barata e atinge uma ameaça por vez.",
        teach_upgrade: "Selecione uma torre para melhorar (2 níveis) ou vender (70% de volta).",
        teach_firewall: "Firewall: rajadas curtas em área. Ótimo onde a rota faz curvas.",
        teach_spam: "Pacotes de Spam são rápidos e frágeis. Lentidão e dano em área resolvem.",
        teach_traffic: "Controlador de Tráfego: deixa tudo ao redor mais lento (máx. 50%, não acumula).",
        teach_backup: "Estação de Backup: não ataca, mas dá turbo a torres vizinhas. O turbo não acumula.",
        teach_reboot: "Reboot de Emergência: toque no botão e depois no mapa. As torres da área ficam 3 s offline e voltam limpas e mais rápidas.",
        teach_trojan: "Pacote Trojan: ao ser derrotado solta 3 Bugs. Tenha dano em área por perto!",
        teach_scanner: "Scanner de Segurança: revela ameaças ocultas. Na próxima onda você vai precisar.",
        teach_stealth: "Pacotes Ocultos só podem ser atingidos enquanto um Scanner os revela (eles ficam brilhantes).",
        teach_lock: "Ransomware bloqueia uma torre próxima por 4 s (com contagem). Um Reboot limpa o bloqueio.",
        teach_boss: "Chefe final: o Deploy de Sexta é lento, mas solta Spam ao perder 75%, 50% e 25% da vida.",
        stats: "Resultado", defeated: "Ameaças resolvidas", escaped: "Escapadas", time: "Tempo", newBest: "Novo recorde!"
    },
    en: {
        title: "IT Operations", subtitle: "Defend the Datacenter",
        play: "Play", howto: "How to play", settings: "Settings", back: "Back", resume: "Resume", restart: "Restart",
        quit: "Quit", ok: "Got it", close: "Close",
        premise: "Friday, 5 pm. The IT team was about to leave when the monitoring dashboard lit up.\nKeep the datacenter online until the incident is resolved!",
        credits: "Credits", health: "Service Health", wave: "Wave", enemies: "Threats", remaining: "left",
        startWave: "Start wave", nextWave: "Next wave", speedNormal: "1x", speedFast: "2x", pause: "Pause", paused: "Game paused",
        build: "Build", upgrade: "Upgrade", sell: "Sell", cancel: "Cancel", level: "Level", max: "Max",
        range: "Range", damage: "Damage", rate: "Shots/s", slow: "Slow", splash: "Area", boost: "Boost", period: "Every",
        reboot: "Emergency Reboot", rebootHint: "Tap the map: towers in the area reboot (3 s offline), then come back clean and faster.",
        rebootReady: "Ready", rebootCooldown: "Recharging", rebootEmpty: "No tower in that area.",
        noCredits: "Not enough credits.", occupied: "That socket already has a tower.", placeHere: "Tap a blue socket to build.",
        victory: "Incident resolved!", victoryText: "The datacenter stayed online. Have a great weekend, team!",
        defeat: "The service went down…", defeatText: "Happens to everyone. Restart and try a different mix of towers.",
        best: "Best results", bestWave: "Best wave", wins: "Wins", fastest: "Fastest win", none: "—",
        language: "Language", volume: "Volume", mute: "Mute", reducedFx: "Reduced effects", on: "On", off: "Off",
        socket: "Placement socket", socketHint: "Pick a tower below. The circle shows the range before you buy.",
        hint_corners: "Covers two stretches of the route.", hint_splash: "Great for area damage.", hint_support: "Close to other towers: good for support.",
        hint_range: "Far from the route: prefer long range.", hint_entrance: "Near the entrance: threats are still grouped.",
        disabled: "Locked", offline: "Rebooting", incoming: "Incoming", ready: "Ready?",
        tower_patch: "Patch Station", tower_patch_desc: "A technician's laptop. Fires data pulses at one threat at a time. Cheap and reliable.",
        tower_firewall: "Firewall", tower_firewall_desc: "A chunky appliance with a shield panel. Short bursts that hit groups.",
        tower_traffic: "Traffic Controller", tower_traffic_desc: "A network switch. Slows nearby threats for a few seconds (50% at most).",
        tower_scanner: "Security Scanner", tower_scanner_desc: "A scanning monitor. Reveals concealed threats in range and deals modest damage.",
        tower_backup: "Backup Station", tower_backup_desc: "A UPS. Does not attack: periodically gives a nearby tower a speed boost.",
        enemy_bug: "Bug", enemy_bug_desc: "A mischievous orange block. Common, average speed and health.",
        enemy_spam: "Spam Packet", enemy_spam_desc: "A hurried yellow envelope. Fast and fragile, comes in groups.",
        enemy_trojan: "Trojan Package", enemy_trojan_desc: "A purple box with a suspicious seam. Releases 3 Bugs when defeated!",
        enemy_stealth: "Stealth Packet", enemy_stealth_desc: "A nearly invisible cyan diamond. Can only be hit while a Scanner reveals it.",
        enemy_lock: "Ransomware Lock", enemy_lock_desc: "A heavy red padlock. Slow, durable, and locks a nearby tower for a few seconds.",
        enemy_boss: "Friday Deployment", enemy_boss_desc: "A giant unstable software package. Slow, and releases Spam groups as it loses health.",
        w1: "Someone clicked the attachment.", w2: "It worked in staging.", w3: "The intern ran the script in production.", w4: "Inbox: 9,999 new messages.",
        w5: "“It's just a tiny package, trust me.”", w6: "Emergency maintenance!", w7: "Beware of gifts.", w8: "The vendor swears it's safe.",
        w9: "Suspicious traffic on switch 3.", w10: "Something is hiding in the logs…", w11: "The antivirus is “updating”.", w12: "Nobody reads the changelog.",
        w13: "Your files have been… wait, no!", w14: "Backup? What backup?", w15: "Friday deployment.",
        teach_place: "Tap a blue socket beside the route and pick a tower. The circle shows the range before you spend.",
        teach_patch: "Start with the Patch Station: cheap, hits one threat at a time.",
        teach_upgrade: "Select a tower to upgrade it (2 levels) or sell it (70% back).",
        teach_firewall: "Firewall: short area bursts. Great where the route bends.",
        teach_spam: "Spam Packets are fast and fragile. Slowing and area damage handle them.",
        teach_traffic: "Traffic Controller: slows everything around it (50% max, never stacks).",
        teach_backup: "Backup Station: does not attack, but boosts neighbouring towers. Boosts never stack.",
        teach_reboot: "Emergency Reboot: press the button, then tap the map. Towers in the area go offline for 3 s and come back clean and faster.",
        teach_trojan: "Trojan Package: releases 3 Bugs when defeated. Keep area damage nearby!",
        teach_scanner: "Security Scanner: reveals concealed threats. You will need it next wave.",
        teach_stealth: "Stealth Packets can only be hit while a Scanner reveals them (they light up).",
        teach_lock: "Ransomware locks a nearby tower for 4 s (with a countdown). A Reboot clears the lock.",
        teach_boss: "Final boss: the Friday Deployment is slow but releases Spam at 75%, 50% and 25% health.",
        stats: "Result", defeated: "Threats resolved", escaped: "Escaped", time: "Time", newBest: "New best!"
    },
    de: {
        title: "IT-Einsatz", subtitle: "Verteidige das Rechenzentrum",
        play: "Spielen", howto: "Anleitung", settings: "Einstellungen", back: "Zurück", resume: "Weiter", restart: "Neu starten",
        quit: "Beenden", ok: "Verstanden", close: "Schließen",
        premise: "Freitag, 17 Uhr. Das IT-Team wollte gerade gehen, als das Monitoring-Dashboard aufleuchtete.\nHalte das Rechenzentrum online, bis der Vorfall behoben ist!",
        credits: "Credits", health: "Dienstzustand", wave: "Welle", enemies: "Bedrohungen", remaining: "übrig",
        startWave: "Welle starten", nextWave: "Nächste Welle", speedNormal: "1x", speedFast: "2x", pause: "Pause", paused: "Spiel pausiert",
        build: "Bauen", upgrade: "Aufrüsten", sell: "Verkaufen", cancel: "Abbrechen", level: "Stufe", max: "Max.",
        range: "Reichweite", damage: "Schaden", rate: "Schüsse/s", slow: "Verlangsamung", splash: "Fläche", boost: "Turbo", period: "Alle",
        reboot: "Notfall-Neustart", rebootHint: "Tippe auf die Karte: die Türme im Bereich starten neu (3 s offline) und kommen sauber und schneller zurück.",
        rebootReady: "Bereit", rebootCooldown: "Lädt auf", rebootEmpty: "Kein Turm in diesem Bereich.",
        noCredits: "Nicht genug Credits.", occupied: "Auf diesem Platz steht schon ein Turm.", placeHere: "Tippe auf einen blauen Platz, um zu bauen.",
        victory: "Vorfall behoben!", victoryText: "Das Rechenzentrum blieb online. Schönes Wochenende, Team!",
        defeat: "Der Dienst ist ausgefallen…", defeatText: "Passiert jedem. Starte neu und probiere eine andere Turmkombination.",
        best: "Beste Ergebnisse", bestWave: "Beste Welle", wins: "Siege", fastest: "Schnellster Sieg", none: "—",
        language: "Sprache", volume: "Lautstärke", mute: "Stumm", reducedFx: "Weniger Effekte", on: "An", off: "Aus",
        socket: "Bauplatz", socketHint: "Wähle unten einen Turm. Der Kreis zeigt die Reichweite vor dem Kauf.",
        hint_corners: "Deckt zwei Abschnitte der Route ab.", hint_splash: "Ideal für Flächenschaden.", hint_support: "Nah an anderen Türmen: gut für Unterstützung.",
        hint_range: "Weit von der Route: lieber große Reichweite.", hint_entrance: "Nah am Eingang: die Bedrohungen sind noch gebündelt.",
        disabled: "Gesperrt", offline: "Neustart", incoming: "Im Anmarsch", ready: "Bereit?",
        tower_patch: "Patch-Station", tower_patch_desc: "Der Laptop eines Technikers. Feuert Datenimpulse auf eine Bedrohung nach der anderen. Günstig und zuverlässig.",
        tower_firewall: "Firewall", tower_firewall_desc: "Ein robustes Gerät mit Schild-Panel. Kurze Salven, die Gruppen treffen.",
        tower_traffic: "Traffic-Controller", tower_traffic_desc: "Ein Netzwerk-Switch. Verlangsamt Bedrohungen in der Nähe einige Sekunden (höchstens 50 %).",
        tower_scanner: "Sicherheits-Scanner", tower_scanner_desc: "Ein Monitor zum Scannen. Enttarnt versteckte Bedrohungen in Reichweite und macht mäßigen Schaden.",
        tower_backup: "Backup-Station", tower_backup_desc: "Eine USV. Greift nicht an: gibt regelmäßig einem Nachbarturm einen Geschwindigkeits-Turbo.",
        enemy_bug: "Bug", enemy_bug_desc: "Ein frecher orangefarbener Klotz. Häufig, mittlere Geschwindigkeit und Lebenspunkte.",
        enemy_spam: "Spam-Paket", enemy_spam_desc: "Ein eiliger gelber Umschlag. Schnell und zerbrechlich, kommt in Gruppen.",
        enemy_trojan: "Trojaner-Paket", enemy_trojan_desc: "Eine lila Kiste mit verdächtiger Naht. Setzt beim Besiegen 3 Bugs frei!",
        enemy_stealth: "Tarnpaket", enemy_stealth_desc: "Eine fast unsichtbare türkise Raute. Nur zu treffen, solange ein Scanner sie enttarnt.",
        enemy_lock: "Ransomware-Schloss", enemy_lock_desc: "Ein schweres rotes Vorhängeschloss. Langsam, zäh, und sperrt einen Turm in der Nähe für einige Sekunden.",
        enemy_boss: "Freitags-Deployment", enemy_boss_desc: "Ein riesiges, instabiles Softwarepaket. Langsam, und setzt beim Verlieren von Lebenspunkten Spam-Gruppen frei.",
        w1: "Jemand hat den Anhang geklickt.", w2: "Auf Staging lief es.", w3: "Der Praktikant hat das Skript in Produktion gestartet.", w4: "Posteingang: 9.999 neue Nachrichten.",
        w5: "„Nur ein kleines Paket, vertrau mir.“", w6: "Notfallwartung!", w7: "Ein Geschenk mit Haken.", w8: "Der Anbieter schwört, es sei sicher.",
        w9: "Verdächtiger Traffic auf Switch 3.", w10: "Irgendetwas versteckt sich in den Logs…", w11: "Der Virenscanner „aktualisiert“ gerade.", w12: "Niemand liest das Changelog.",
        w13: "Ihre Dateien wurden… Moment, nein!", w14: "Backup? Welches Backup?", w15: "Freitags-Deployment.",
        teach_place: "Tippe auf einen blauen Platz neben der Route und wähle einen Turm. Der Kreis zeigt die Reichweite vor dem Kauf.",
        teach_patch: "Fang mit der Patch-Station an: günstig, trifft eine Bedrohung nach der anderen.",
        teach_upgrade: "Wähle einen Turm, um ihn aufzurüsten (2 Stufen) oder zu verkaufen (70 % zurück).",
        teach_firewall: "Firewall: kurze Flächensalven. Ideal, wo die Route abbiegt.",
        teach_spam: "Spam-Pakete sind schnell und zerbrechlich. Verlangsamung und Flächenschaden helfen.",
        teach_traffic: "Traffic-Controller: verlangsamt alles in der Nähe (max. 50 %, stapelt nie).",
        teach_backup: "Backup-Station: greift nicht an, gibt aber Nachbartürmen Turbo. Turbo stapelt nie.",
        teach_reboot: "Notfall-Neustart: Knopf drücken, dann auf die Karte tippen. Die Türme im Bereich sind 3 s offline und kommen sauber und schneller zurück.",
        teach_trojan: "Trojaner-Paket: setzt beim Besiegen 3 Bugs frei. Halte Flächenschaden bereit!",
        teach_scanner: "Sicherheits-Scanner: enttarnt versteckte Bedrohungen. In der nächsten Welle brauchst du ihn.",
        teach_stealth: "Tarnpakete sind nur zu treffen, solange ein Scanner sie enttarnt (sie leuchten dann auf).",
        teach_lock: "Ransomware sperrt einen Turm in der Nähe für 4 s (mit Countdown). Ein Neustart hebt die Sperre auf.",
        teach_boss: "Endgegner: das Freitags-Deployment ist langsam, setzt aber bei 75 %, 50 % und 25 % Lebenspunkten Spam frei.",
        stats: "Ergebnis", defeated: "Bedrohungen behoben", escaped: "Entkommen", time: "Zeit", newBest: "Neuer Rekord!"
    }
}
